version: "3.8"
   
services:
  app:
    network_mode: "host"
    build: .
    image: whoishome
    command: python /mysite/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DEBUG=True
      - DJANGO_DBPATH=/dbstore/db_whoih.sqlite3
    ports:
      - ${WHOIH_PORT}:8000
    restart: always
    volumes:
      - dbstore:/dbstore
      # - ./mysite:/mysite
    depends_on:
      - migration
      
  migration:
    network_mode: "host"
    build: .
    image: whoishome
    command: python manage.py migrate --noinput
    environment:
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DEBUG=True
      - DJANGO_DBPATH=/dbstore/db_whoih.sqlite3
    volumes:
      - dbstore:/dbstore
      # - ./mysite:/mysite

volumes:
  dbstore: