services:
  web:
    network_mode: "host"
    image: dartlazer/whoishome-ui:v0.7
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"
    environment:
      - DJANGO_TZ=${WHOIH_TZ}
      - DJANGO_DBPATH=/dbstore/db.sqlite3
    restart: always
    volumes:
      - dbstore:/dbstore

  scanner:
    network_mode: "host"
    image: byrnedo/alpine-curl
    command: [ "sleep", "60s", "&&", "curl", "-s", "http://0.0.0.0:${WHOIH_PORT}/scan/" ]
    restart: always

volumes:
  dbstore:
