# Generated by Django 3.2.15 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0007_homepagesettingsconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_required', models.BooleanField(default=False)),
            ],
        ),
    ]
