# Generated by Django 3.2.15 on 2022-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0005_auto_20220817_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerconfig',
            name='scanner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='arrival_mail_body',
            field=models.CharField(default='{target} has arrived home at time {arrival_time}', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='arrival_mail_suject',
            field=models.CharField(default='{target} has arrived home.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='departure_mail_body',
            field=models.CharField(default='{target} has left home at time {departure_time}.', max_length=500),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='departure_mail_subject',
            field=models.CharField(default='{target} has left home.', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='sender_address',
            field=models.CharField(default='test@test.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_domain',
            field=models.CharField(default='smtp@test.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_port',
            field=models.CharField(default='465', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='to_address',
            field=models.CharField(default='to@test.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='your_password',
            field=models.CharField(default='secretpassword', max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='arp_string',
            field=models.CharField(default='arp-scan --interface=', max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='internet_interface',
            field=models.CharField(default='eth0', max_length=15),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='ip_range_end',
            field=models.CharField(default='198', max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='ip_range_start',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='ip_subnet',
            field=models.CharField(default='192.168.2.', max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerconfig',
            name='not_home_treshold',
            field=models.IntegerField(default=21),
        ),
    ]
