# Generated by Django 3.2.15 on 2022-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0006_auto_20220819_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettingsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_all_devices', models.BooleanField(default=False)),
            ],
        ),
    ]
