# Generated by Django 4.2.4 on 2023-08-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0011_auto_20230216_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_switch', models.BooleanField(default=False)),
                ('bot_token', models.CharField(blank=True, max_length=256)),
                ('chat_id', models.CharField(blank=True, max_length=256)),
                ('arrival_message', models.CharField(max_length=500)),
                ('departure_message', models.CharField(max_length=500)),
                ('curfew_message', models.CharField(default='At time {arrival_time} device {target} connected during curfew time', max_length=500)),
                ('new_connection_message', models.CharField(default='At time {arrival_time} a new device connected to the network\nMAC: {mac}\nIP: {ip}\nName: {name}', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_delete_after_x_days',
            field=models.IntegerField(default=0),
        ),
    ]
