# Generated by Django 4.2.4 on 2023-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0013_initialize_telegramnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationsconfig',
            name='new_device_detected_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
