# Generated by Django 4.2.16 on 2024-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoishome', '0014_telegramnotificationsconfig_new_device_detected_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
    ]
